macro(add_subdirectories)
    file(GLOB SUBDIRECTORIES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/*)
    foreach(SUBDIRECTORY ${SUBDIRECTORIES})
        file(RELATIVE_PATH SUBDIRECTORY_RELATIVE ${NOX_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/${SUBDIRECTORY})
        if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${SUBDIRECTORY}/CMakeLists.txt)
            add_subdirectory(${SUBDIRECTORY})
        endif()
    endforeach()
endmacro()

macro(create_project_source_tree TARGET)
    if(MSVC)
        set(PREFIXES ${CMAKE_CURRENT_SOURCE_DIR} ${ARGN} ${NOX_SOURCE_DIR})
        get_target_property(PRIVATE_SOURCE_LIST ${TARGET} SOURCES)
        get_target_property(INTERFACE_SOURCE_LIST ${TARGET} INTERFACE_SOURCES)
        set(SOURCE_LIST ${PRIVATE_SOURCE_LIST} ${INTERFACE_SOURCE_LIST})
        foreach(SOURCE_FILE ${SOURCE_LIST})
            if(NOT ${SOURCE_FILE} MATCHES "\<*\>")
                string(TOLOWER ${SOURCE_FILE} SOURCE_FILE_RELATIVE)
                foreach(PREFIX ${PREFIXES})
                    if(SOURCE_FILE_RELATIVE)
                        string(TOLOWER ${PREFIX} PREFIX)
                        string(REPLACE "${PREFIX}" "" SOURCE_FILE_RELATIVE ${SOURCE_FILE_RELATIVE})
                    endif()
                endforeach()

                get_filename_component(SOURCE_PATH_RELATIVE ${SOURCE_FILE_RELATIVE} PATH)
                if(SOURCE_PATH_RELATIVE)
                    string(REPLACE "/" "\\" SOURCE_PATH_RELATIVE ${SOURCE_PATH_RELATIVE})
                endif()

                get_filename_component(INCLUDE_DIRECTORY ${SOURCE_FILE_RELATIVE} DIRECTORY)
                if(INCLUDE_DIRECTORY)
                    string(REPLACE "/" "\\" INCLUDE_DIRECTORY ${INCLUDE_DIRECTORY})
                endif()

                if(INCLUDE_DIRECTORY MATCHES ".include.")
                    source_group("${INCLUDE_DIRECTORY}" FILES ${SOURCE_FILE})
                else()
                    source_group("${SOURCE_PATH_RELATIVE}" FILES ${SOURCE_FILE})
                endif()
            endif()
        endforeach()
    endif()
endmacro()
